pipeline {
    
    agent { label 'worker_agent' }
    
    environment {
        MONGO_TEST = credentials('MONGODB_TEST_URL')
        REDIS_HOST = credentials('REDIS_HOST')
        REDIS_PORT = credentials('REDIS_PORT')
        DOCKER_USERNAME = credentials('DOCKER_USERNAME')
        IMAGE_NAME = "${DOCKER_USERNAME}/cloudvault-backend:${BUILD_NUMBER}"
        USER_EMAIL = credentials('ALERT_EMAIL')
    }
    
    stages {

        stage('Install dependency') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }
        
        stage('Run test') {
            steps {
                dir('backend') {
                    sh 'export MONGODB_TEST_URL=$MONGO_TEST'
                    sh 'export REDIS_HOST=$REDIS_HOST'
                    sh 'export REDIS_PORT=$REDIS_PORT'
                    sh 'cross-env NODE_ENV=test npm test'
                    echo 'Test successful'
                }
            }
        }
        
        stage('Build image') {
            steps {
                dir('backend') {
                    echo 'Starting image build...'
                    sh 'docker build -t $IMAGE_NAME .'
                    echo 'Build successful'
                }
            }
        }

        stage('Scan image') {
            steps {
                echo 'Starting image scanning...'
                sh 'trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME'
                echo 'Scan completed'
            }
        }

        stage('Push to registry') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'DOCKERHUB_CREDS',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    echo 'Pushing image to registry...'
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push $IMAGE_NAME'
                    echo 'Image pushed to registry'
                }
            }
        }
    }

    post {
        success {
            mail to: $USER_EMAIL,
            subject: "SUCCESS ! Pipeline executed",
            body: "Cloudvault backend pipeline executed successfully."
        }
        
        failure {
            mail to: $USER_EMAIL,
            subject: "ERROR ! Pipeline stopped",
            body: "Cloudvault backend pipeline stopped due to error. View logs for problem identification."
        }

        always {
            echo 'Pipeline execution completed'
        }
    }
}



